<?php
/**
 * LEGACY FILE — DO NOT EDIT THIS FILE.
 *
 * This file has been superseded by template-parts/home/values.php
 * and is kept only to prevent 404s if any cached/old code references it.
 *
 * The homepage section manager now points to values.php.
 * All edits should be made in values.php.
 */
get_template_part('template-parts/home/values');
